### ISSUE TITLE
[FIX] Updates to match the exact workshop details

### ISSUE THREAD

**Issue by ree-gupta** [lmu-osc/2024-08-01-LMU#1]
- [ ] Is the slug `2024-08-01-LMU` alright or if the site needs to be more specific?
- [ ] Make repo public to test gh-pages
- [ ] I took the liberty to use people’s email and names in the website, hope that is okay?
- [ ] Do we use carpentries pad of pads for collaborative notes or OSC has something or set-up of our own?
- [ ] Decide for either `swc-inflammation` or `swc-gapminder`? Tentatively I have used inflammation
- [ ] Decide on workshop title - tentatively - “LMU Martinsried Software Carpentry”
- [ ] Update README and website repo description

**Comment by LuisaFJimenez** [comment]
Thanks Reema!!! Sent from my phone while I am on the road. Please forgive any spelling mistakes. Short answers are a necessity while typing with thumbs 😀 
-------- Original message --------From: Reema Gupta ***@***.***> Date: 7/1/24  18:10  (GMT+01:00) To: lmu-osc/2024-08-01-LMU ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [lmu-osc/2024-08-01-LMU] [FIX] Updates to match the exact
  workshop details (Issue #1) 
Closed #1 as completed.
